### ISSUE TITLE
Use pre-existing image folders

### ISSUE THREAD

**Issue by anewuser** [theMK2k/MetropolisLauncher#11]
From what I've seen, you've only developed ways to import images manually for each game or created while an emulator is running a specific game. 

Please consider adding an option to specify directories that already contain images (snapshots, title screens etc.) for a platform.

MAME users can download full sets of images from [Progetto Snaps](http://www.progettosnaps.net/snapshots/), and people who use No-Intro/Redump ROMs can download collections of screenshots and box arts from https://github.com/libretro/libretro-thumbnails/ . Both offer images that have the same names as the expected ROM file names.

Here's how you set the directories up on [QuickPlay](http://quickplay.sourceforge.net/):

![1](https://user-images.githubusercontent.com/6733770/27775657-8a80c418-5f7a-11e7-94cf-addaf17eea01.png)

The filename drop-down menu:

![2](https://user-images.githubusercontent.com/6733770/27775659-8db40cb2-5f7a-11e7-92fa-0c67d65c33e0.png)

Result after specifying the folders with all images:

![3](https://user-images.githubusercontent.com/6733770/27775683-be2ce63e-5f7a-11e7-8e52-c28ac2942d32.png)

**Comment by theMK2k** [comment]
Hey @anewuser, Metropolis Launcher already works with files on a per-name basis. The directories which Metropolis Launcher expects are already shipped with the release (it is the "extras\emulation" directory incl. subdirectories. Of course you can fill them with downloaded snapshot packs.

Documentation: [https://documentation.metropolis-launcher.net/index.html?extras_screenshots_etc_.htm](https://documentation.metropolis-launcher.net/index.html?extras_screenshots_etc_.htm)

**Comment by theMK2k** [comment]
I see you request some import functionality. I currently vote against it, because it is simply a task of
- download extras pack
- copy or move the files in the expected directories

This is more or less the same with downloaded MAME extras packs and the MameUI launcher.

RetroArch is able to auto-download extras, which could be a nice feature for Metropolis Launcher in the future. The RetroArch boxarts are of questionable quality though.

**Comment by anewuser** [comment]
I missed that help page, sorry.

And no, I didn't mean to "import" (copy) the images. I meant to read them directly from the custom paths provided, but I understand that you prefer to keep everything organized under your application directory, and users may create symlinks in case they want to use other locations.

**Comment by theMK2k** [comment]
No worries, that's why issues are for :)

The directory structure doesn't have to be under the application's installation dir, you can set it up in the Settings window next to "Extras Directory".

See [3] in [http://documentation.metropolis-launcher.net/index.html?settings.htm](http://documentation.metropolis-launcher.net/index.html?settings.htm)
