### ISSUE TITLE
Request: Customized launcher skins

### ISSUE THREAD

**Issue by cirdansky** [theMK2k/MetropolisLauncher#48]
Hi!

Would be possible to add a feature to customize launcher's skins? 
Or maybe there is already a way?
Thanks!

**Comment by theMK2k** [comment]
@cirdansky thanks for your request, unfortunately this is not easily possible.

In order to create a customized skin, you need the [Devexpress Winforms Skin Editor](https://docs.devexpress.com/SkinEditor/1630/winforms-skin-editor), which can't be downloaded freely.

Also, after creating the skin it must be registered with the application. This is only possible by compiling it with the custom skin. <https://docs.devexpress.com/SkinEditor/2546/export-and-apply-custom-skins>
